#!/usr/bin/env python
#
# Copyright (C) 2014  Leo Singer
#
# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation; either version 2 of the License, or (at your
# option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General
# Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#
"""
Example VOEvent listener that saves all incoming VOEvents to disk.

The default server is "68.169.57.253:8099".
"""
__author__ = "Leo Singer <leo.singer@ligo.org>"
import json

import ephem
import sys

from util.handlers import T80SHandlerClass

with open(sys.argv[1]) as fp:
    configuration = json.load(fp)

# TODO: remove this. only for tests.
if not 'packet_types' in configuration:
    configuration['packet_types'] = range(1000)
# 'packet_types': [60, 61, 62, 63, 64, 65], 'min_grb_alt': .523598776, 'max_extinction': 100.0}

# TODO: Add extinction check
# TODO: Add to Zenoss pygcn-list check

from util import handlers as t80s_handlers

# Init Observatory Ephem calculator.
observatory = ephem.Observer()
observatory.lon = configuration['observatory.lon']
observatory.lat = configuration['observatory.lat']
observatory.elevation = configuration['observatory.elevation']

# Imports
import gcn.notice_types
import logging

# T80S decorators

# Set up logger
logging.basicConfig(level=logging.INFO)

# Listen for GCN notices (until interrupted or killed)
HandlerClass = T80SHandlerClass(configuration, observatory)
gcn.listen(host=configuration['gcn_host'], port=configuration['gcn_port'], handler=HandlerClass)
